### ISSUE TITLE
Service Property Values are No Good for Logins

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-amplitude-send#28]
I can't find sync in the property service for login events. There is also a bunch of unreadable events.

<img width="403" alt="image" src="https://user-images.githubusercontent.com/19537086/32809529-fd227940-c94b-11e7-9cc7-0c34ca95bccf.png">

I do see it in registrations though but it too has a lot of garbage:
<img width="405" alt="image" src="https://user-images.githubusercontent.com/19537086/32809498-dda7f4e6-c94b-11e7-8c8d-baa95e67430e.png">

**Comment by philbooth** [comment]
I think there's three distinct issues in here.

1. The configs for the content and auth servers are missing definitions for a bunch of OAuth client ids. I will raise this separately with the two j's.

2. Is the current behaviour of including the raw client id if we don't have a definition for it correct? When I wrote this stuff I figured it was because at least it tells us that the event is from an OAuth flow, and it is theoretically possible for us to go and look them up if we want. But maybe that's impractical and we'd prefer just not knowing whether they're OAuth events if we don't have the definition.

3. The main issue, which is the missing Sync `fxa_login - complete` events. This is happening because at the point where we emit that event, we don't have the service available to us right now. We can fix it in one of two ways: either store it in memcached with the metrics context or promote `service` to be a user property in Amplitude. I'm fine with either of those, maybe leaning slightly towards the former.

In the meantime @davismtl, you can see Sync login events by using `fxa_login - success` instead. We always have the service available when we emit that event and I've checked you can see it in Amplitude. I realise it's not ideal but hopefully it lets you get some analysis done in the short term.

**Comment by davismtl** [comment]
Thanks for the details @philbooth . Very helpful.

**Comment by philbooth** [comment]
@davismtl, concerning this question:

> 2. Is the current behaviour of including the raw client id if we don't have a definition for it correct?

Would it be better from your perspective if I fell back to using some common known string like "undefined oauth client" in the code, whenever I get a client id which has no mapping defined in config? At least then it would put a stop to the proliferation of meaningless hex values in the dropdowns in Amplitude, but it would still offer some insight that the flow is for an OAuth relier.

**Comment by davismtl** [comment]
Sure this makes sense. I'm sure any of these would work: "undefined oauth client" or ""undefined" or "unknown", etc...
