### ISSUE TITLE
Login success double counting?

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-amplitude-send#29]
I'm wondering if we're double counting login success, as it generally seems to have more events than login submit.

https://analytics.amplitude.com/org/31251/chart/20v34dk

**Comment by vladikoff** [comment]
from mtg: use funnel 

![image](https://user-images.githubusercontent.com/128755/33029756-6ce4542a-cde7-11e7-90dd-9bd5683f140c.png)

**Comment by philbooth** [comment]
In the linked chart, if you remove the filtering on `fxa_services_used: sync`, the problem disappears.

`fxa_services_used` is a funny property because the content server doesn't emit it, only the auth server. So there will always be a bunch of people for whom it isn't set, e.g. wrong email/password and they give up without ever hitting the back-end.

And there's also the question of how Amplitude treats user properties, I thought they're only visible for events that occur after they've been set, which would mean even more people aren't being counted by this chart (although note that @davismtl disagreed with my interpretation in the meeting just now so maybe it's a red herring).

And even leaving aside those two points, `fxa_services_used` is worth being wary of because we know it's incomplete because of how we're relying on Amplitude's `$append` stuff to gradually update it for us.

So instead of the `fxa_services_used` user property, you probably want the `service` event property. I think that one is more accurate on a per-event basis although there's also an open issue about problems with it so maybe not.

But anyway, there's no sign of double counting if you ditch `fxa_services_used` so I'm hoping that is not a thing.

**Comment by davismtl** [comment]
To support what @philbooth was saying, you should use `service` property on event. If you look at this, it makes sense.

https://analytics.amplitude.com/org/31251/chart/20v34dk/edit/iqfzp7z

`fxa_services_used` just keeps track of any relier service you've ever signed into. It's a way to globally track how many users use Sync, AMO, etc...

So what were you looking at? Submit vs success where the users have **ever** used Sync. Should these be similar? Probably but there are some scenario like Pocket which don't require a Form Submit to have a login Success.

**Comment by davismtl** [comment]
CC @irrationalagent for context.

**Comment by davismtl** [comment]
> And there's also the question of how Amplitude treats user properties, I thought they're only visible for events that occur after they've been set, which would mean even more people aren't being counted by this chart (although note that @davismtl disagreed with my interpretation in the meeting just now so maybe it's a red herring).

You have me doubting @philbooth . I think you may be right though. I don't think user_properties are retro-active.

**Comment by vladikoff** [comment]
Resolved:

* Remove `service_used` , it's bad
* Worried that content server can be dropped if validation fails. Auth server always accepts. This way the submits might be missing from Amplitude.

**Comment by vladikoff** [comment]
Use a funnel

**Comment by philbooth** [comment]
Also, a possible cause for this might be that content server events (i.e. submit in this case) are not being emitted due to validation errors on `POST /metrics`. The auth server has no equivalent validation on utm params etc, so it's probably possible for login success to be emitted without there being a corresponding submit event? I think?
