### ISSUE TITLE
Login Success then Login Submit

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-amplitude-send#31]
Success to Submit funnel looks strange: https://analytics.amplitude.com/org/31251/chart/8e4s37q

cc @davismtl

**Comment by philbooth** [comment]
Isn't this just because you've got the events the wrong way round? Up at the top where it says "events performed in this order", you have success *before* submit. So this is showing people who successfully signed in and then at some later point had another sign-in attempt.

Instead, if you drag success down so it is after submit, the chart looks okay to me.

**Comment by vladikoff** [comment]
> Instead, if you drag success down so it is after submit, the chart looks okay to me.

We intentionally put it in the wrong order to see what would happen. I'm guessing we were looking to have that number be close to 0 when we change it to `previous 1 day only`

**Comment by philbooth** [comment]
Oops, sorry!

**Comment by davismtl** [comment]
@vladikoff So... I'm hesitant about this being wrong. I think the numbers make sense.

If you click on the last step of funnel, you can inspect users and see the event stream they've generated. The first 10 that I looked at all logged in to 2 devices. 

From what I am seeing, this would mean that your funnel results are accurate.

The first step is triggered the first time they login to a device. The second step is triggered if they try to login to any other device.

You picked a 30 day date range but when you dig in more, you can see that 50% of the users are since the Quantum launch. This supports a something I shared in show and tell. Existing users are adding more devices since Quantum launch. (since there doesn't seem to be any report of bugs relating to accounts)

Does this make sense to you?

CC @irrationalagent @ryanfeeley

**Comment by shane-tomlinson** [comment]
Decision from meeting - fine for now. Strange as it is.
