### ISSUE TITLE
Decompression should call flush() to avoid truncating data

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-amplitude-send#35]
The `decompress` function here:

  https://github.com/mozilla/fxa-amplitude-send/blob/de521bc47727f44e1167d289c0d5999166cf5c42/amplitude.py#L75

Might leave unconsumed data in internal decompression buffers.  IIUC you have to call the `flush()` method on the decompressor object in order to ensure all buffered data is consumed:

  https://docs.python.org/3.5/library/zlib.html#zlib.Decompress.flush

**Comment by philbooth** [comment]
Again I'm probably talking out of my backside here, but that's not the behaviour I see when I test it and it's also not what I took from reading those docs you link to.

When I apply these changes to the script:

```
diff --git a/amplitude.py b/amplitude.py
index aaecdfc..500893a 100644
--- a/amplitude.py
+++ b/amplitude.py
@@ -63,17 +63,19 @@ def process_compressed (pool, data):
     events = ""
     batches = None

-    for chunk in decompress(data):
+    decompressor = zlib.decompressobj(ZLIB_WBITS)
+    for chunk in decompress(data, decompressor):
         events += chunk
         partitioned_events = partition_available_events(events)
         if is_partitioned(partitioned_events):
             events = partitioned_events[2]
             batches = process(pool, partitioned_events[0], batches, False)
+    remaining = decompressor.flush()
+    print len(remaining)

     process(pool, events, batches)

-def decompress (data):
-    decompressor = zlib.decompressobj(ZLIB_WBITS)
+def decompress (data, decompressor):
     for chunk in data:
         decompressed = decompressor.decompress(chunk)
         if decompressed:
```

...and run it against all the stage data I have (54 files), all I see from that `print` statement is zeroes.

My naive take on what's written in the docs is that `flush` doesn't return data in our case because there's no pending input left to process. We called `decompress` until it's all gone, because of that outer loop in `process_compressed`.

Having said all that, obviously no harm that can come from calling it and maybe my tests aren't properly exercising stuff like the real pipeline does. So I'll definitely open a PR to fix it, just wanted to flag that I'm not sure this is the cause of our missing events in Amplitude is all.

**Comment by rfk** [comment]
Sounds good; I do think it's worth doing for completeness even if it doesn't show a problem in tests, since the docs for `decompress` [1] warn that:

> "Some of the input data may be preserved in internal buffers for later processing"

[1] https://docs.python.org/3.5/library/zlib.html#zlib.Decompress.decompress

>  just wanted to flag that I'm not sure this is the cause of our missing events in Amplitude is all.

👍 I think that's probably right, even if this were causing us to drop a bit of data in some cases, it wouldn't be as much data as we've seen missing from amplitude on occasion.
