### ISSUE TITLE
Emit tab_transit and node_reassign Amplitude events

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-amplitude-send#46]
The events `sync - tab_transit` and `sync - node_reassign` are respectively high and medium priority in the Amplitude taxonomy. These events will need to be emitted by the Sync server.

(related discussion: https://github.com/mozilla/fxa-amplitude-send/issues/24#issuecomment-341173459)

**Comment by philbooth** [comment]
@rfk, are you the right person to ask about these two events?

I'm interested in finding out:

1. Can they be emitted from back-end Sync server code?
2. Roughly which bit of code are we talking about?
3. Where I can find Sync logs for sending data to Amplitude from? (I guess this one's probably a @jrgm question)

**Comment by rfk** [comment]
> sync - tab_transit

This is an interesting one.  We've actually been emitting an event for this ever since the amplitude PoC because it's something we can see on the FxA server here:

  https://github.com/mozilla/fxa-auth-server/blob/master/lib/routes/devices-and-sessions.js#L325

Except, we can't *really* see it.  We can see when one client tells another client that the sync "clients" collection changed, which often means that it's sending a tab.  But that could also happen for other reasons, so it's not 100% reliable.

The work we're doing with the sync and push teams on "pushbox" is likely to introduce a proper "send tab" push notification type.  Let's check with @davismtl whether the current event is good enough in the meantime, or whether we should defer this one until after the pushbox work gets to a good state.

> sync - node_reassign

This we should be able to detect on the sync tokenserver, which does indeed make @jrgm your man for getting at the logs.

The event you're looking for happens here, where an existing user gets assigned a new node due to operational intervention:

  https://github.com/mozilla-services/tokenserver/blob/master/tokenserver/assignment/sqlnode/sql.py#L274

And also here, where we forcibly move them to a node new after detecting a password reset event:

  https://github.com/mozilla-services/tokenserver/blob/master/tokenserver/assignment/sqlnode/sql.py#L348

I expect it's OK to treat both of those as a single "node re-assignment" event type, possibly with some metadata about the reason why.

I don't recall if we have any existing infrastructure for logging "activity-event" style things from the sync service though; happy to help work through the details of that if you like.

**Comment by davismtl** [comment]
>  Let's check with @davismtl whether the current event is good enough in the meantime, or whether we should defer this one until after the pushbox work gets to a good state.

Defer it. We have sent and received events which are plenty for now.

**Comment by davismtl** [comment]
Already, done. :D 
It is now a low priority event. We can review this in the future.

**Comment by irrationalagent** [comment]
maybe we can close this one? @davismtl seems like we just need to get the send tab events working again first. :coolcry:

**Comment by davismtl** [comment]
We can close this one.
