### ISSUE TITLE
Investigate Android Registration Rate

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-amplitude-send#59]
Our Android registration rate is a lot lower than all of our other OS'. 

https://analytics.amplitude.com/org/31251/chart/i431mal

Verify if we are observing the same thing in Re:Dash.

If it IS NOT as low, investigate Amplitude bug.

If it IS as low, identify Android bug.

**Comment by davismtl** [comment]
CC @irrationalagent

**Comment by irrationalagent** [comment]
https://sql.telemetry.mozilla.org/queries/52198/source#139224

Re:Dash does seem to indicate that android generally has the worst registration rate in relative terms, though in terms of precise numbers its not as low as amplitude indicates. 

Looking at the steps in the funnel, there seems to be a generally even drop off between steps; no single step is contributing disproportionately to the low numbers at first glance:

https://sql.telemetry.mozilla.org/queries/52199/source#139227

Will have to dig in a bit more to know what's going on. There's big variation in Android phones in terms of performance, so my first hunch is that there might be some of that in play here. We know retention and engagement ratio is generally very good on android among all platforms - now I wonder if its because we're filtering out all the bad hardware early on in the process.

**Comment by vladikoff** [comment]
from mtg: look into device, language data

@irrationalagent to group data by locale and others.

**Comment by irrationalagent** [comment]
Taking a quick look at language:

https://analytics.amplitude.com/org/31251/chart/adgtc56

German doing better than English. RTL languages (arabic, persian) certainly worse than the others, but not enough volume there to explain the overall low numbers. 

Probably want to take a look out our persian/arabic. Low English numbers suggest problems beyond localization.

**Comment by irrationalagent** [comment]
There's a clear decrease in registration rate as android version gets older. Still all version underperform windows 10: https://analytics.amplitude.com/org/31251/chart/tpxdfzj

**Comment by davismtl** [comment]
The older the Android version, the older the hardware.

We should probably still test just in case. Anybody have an old device to test with?

@juliemccracken is checking with Softvision to test old Android.

**Comment by juliemccracken** [comment]
Softvision reported back that they have the following older devices:
 Asus Transformer Pad TF300T (Android 4.2.1) - tablet
Lenovo Yoga Tablet 2 (Android 4.4.2) - tablet
Prestigio Grace X5 (Android 4.4.2) - phone
Lenovo A536 (Android 4.4.2) - phone
Will any of these work?

**Comment by irrationalagent** [comment]
Since they're all android 4, I would think that they should serve the purpose. Maybe its best to focus on phones though?

I have a few other questions about this:
- Can we also have them test a new-ish Android 7 phone for comparison?
- Manual or automated tests or both?
- What if, if anything, would we need to provide Softvision with here? Can they just use an existing test plan that they/we have for the FxA registration flow?
- What kind of information can we get back from them? Is it more like "this part crashed, here's the log" or "this part was really slow", or is it more detailed, i.e. how long it took for this or that bit to render?

[Here's](https://analytics.amplitude.com/org/31251/chart/vk4titt) a breakdown of android versions from amplitude, for the clients that report the version (some just report a generic 'android' so I've excluded those).

You can see that the more recent versions are dominant, but I'd say that ~20% of them are versions 5 and below. That's a decent chunk, but I guess my question is: assuming they find that the old phones crash, take forever or otherwise suck during registration, are there scenarios in which we can do something about it? I realize that this probably doesn't have a firm yes or no, but I'm sure others would have a better guess than me. 

My first gut is that it can't hurt to test this, but I also know it's not free. If @mozilla/fxa-devs think that it's likely that there won't be much to be done, then maybe it would be best not to waste QA resources.

**Comment by shane-tomlinson** [comment]
Thank you @irrationalagent for creating so many good charts!

I used [this breakdown by language](https://analytics.amplitude.com/org/31251/chart/adgtc56) to create a new chart that [breaks down by fxa_services_used](https://analytics.amplitude.com/org/31251/chart/pleu60l). 

The two largest groups are "sync" and "none". Sync users convert at ~ 30%, but the more interesting group is "none", which is double the size and registers at 1/6 to 1/3 the rate.

Who are the users in the "none" group and where are they coming from? Are they people that just stumbled on FxA?

**Comment by vladikoff** [comment]
from mtg: will investigate with QA

**Comment by vladikoff** [comment]
from mtg: @irrationalagent can we check device and geo region for Android devices and see which are performing worse?

**Comment by irrationalagent** [comment]
A quick look at a couple things:

Android version, which is probably our best measure related to device age, shows that older versions clearly perform worse:
https://analytics.amplitude.com/mozilla-corp/chart/4w9ym2s

There are some exceptions but generally speaking wealthier regions perform better, again probably because they have better devices (see last column of sorted table below chart).
https://analytics.amplitude.com/mozilla-corp/chart/qg8fvbl

We seem to have 'none' for both device type and device family for most android data, so not a lot to say there. 

Overall my conclusions so far:

1. main story hasn't changed; its still that older os versions just perform worse. Android 8 has a rate better than windows and comparable to mac desktop, for example. So I doubt there's anything inherent to "android" generally that is causing us problems. 
2. I don't see any major trends by region that can't be explained by wealth. E.g. "wealthy" 
Asia performs very well so l10n issues don't seem to be an issue there. 
3. only exception to (2): we might want to take a closer look at Germany, who isn't *terrible* but slightly behind other regions with comparable income. Still within reasonable ranges though. Maybe there's some ugly wrapping or similar problems on smaller screens. 
4. Besides (3) I'm not sure what the next steps here would be - e.g. from an engineering perspective  I'm not sure what we could be doing to accommodate slower devices. Thoughts?

**Comment by davismtl** [comment]
> 1. main story hasn't changed; its still that older os versions just perform worse. Android 8 has a rate better than windows and comparable to mac desktop, for example. So I doubt there's anything inherent to "android" generally that is causing us problems.

But it's still a lot lower than iOS which is a similar form factor. Inversely, could iOS success rates be inflated?

As per the country breakdown, there's clearly a massive problem with China. First step of the funnel seems to be half is much as other countries. View > Engage

@irrationalagent Diving into the funnels, I've noticed the main drop off is happening at the first step compared to other platforms like iOS. (View > Engage)

What could cause there to be a bigger drop off here? I've only noticed one thing.
I noticed that Android continues to display the address bar and has a bunch of exits from the form whereas on iOS, we are opened fullscreen.

**Comment by shane-tomlinson** [comment]
> As per the country breakdown, there's clearly a massive problem with China.

Chinese regulations require Mozilla China to run their own standalone FxA and Sync service for Chinese citizens. China may be so low because most users sign up using Fx Desktop with the Chinese service, then try to sign in on mobile with the non-China service, realize they have no account with us, and bail. We might be able to help these users get to the Chinese service instead of leaving them at a dead end. As such, I'd like to suggest we ignore users from China for these graphs, they aren't supposed to be signing in with us in the first place.

**Comment by davismtl** [comment]
@shane-tomlinson In the long-term, I'd like us to think about how we could provide a better UX for China (which likely means better collaboration with the team there). 

As per the Android performance, my first round of tests has not raised any functional flags. Performance on a Nexus 5 was adequate, although I was on a fast network.

Again, the main problems I saw were related to the first step of the funnel which is probably linked to how FxA is integrated to the browser. I will close this for now.
