### ISSUE TITLE
Investigate TOTP experiment results

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-amplitude-send#64]
While working with @leifoines, we were not able to see any results of the experiment in amplitude. The experiment seems to be setup correctly on the [content-server](https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/lib/experiments/grouping-rules/totp.js). FWIW, no results were also being sent to redash.

@philbooth Anything thoughts on what might be going on?

**Comment by irrationalagent** [comment]
I was wondering if this might be caused by something I did wrong in https://github.com/mozilla/fxa-content-server/pull/6118 but I wasn't able to see anything obvious. We are still receiving experiment name data https://sql.telemetry.mozilla.org/queries/54656/source so I don't think the validation is broken generally (unless all that recent data is from old versions somehow)

**Comment by philbooth** [comment]
Yeah, my first guess was similar to @irrationalagent's, that maybe the new experiment wasn't setting it's `name` so the server validation could pick it up. But the code looks okay on that score. Will dig into it some more...

**Comment by vladikoff** [comment]
@vbudhram we moved it to next in triage

**Comment by vladikoff** [comment]
deployed and getting data
